import { Component, createSignal, createEffect } from 'solid-js';
import styles from './Kepolisian.module.css';
import logo from './image/logo.svg';
import notifikasi from './image/notifikasi.svg';
import riwayat from './image/riwayat.svg';
import search from './image/search.svg';
import iconBeranda from './image/iconBeranda.svg';
import logoKepolisian from './image/logoKepolisian.svg';
import iconTelepon from './image/iconTelepon.svg';
import tambahLokasi from './image/tambahLokasi.svg';
import iconTeleponHover from './image/iconTeleponHover.svg';
import tambahLokasiHover from './image/tambahLokasiHover.svg';